AWSTemplateFormatVersion: 2010-09-09
Description: Conditional execution

Parameters:
    EnvironmentType:
        Description: Select environment type
        Type: String
        AllowedValues: [prod, rc, dev]
        Default: "dev"
    
    MultiBucket:
        Description: Single buckets
        Type: String
        AllowedValues: ["Yes", "No"]
        Default: "No"

Conditions:
    IsProduction: !Or
        - !Equals [!Ref EnvironmentType, prod]
        - !Equals [!Ref EnvironmentType, rc]
    
    IsMultiBucket:
        !Equals [!Ref MultiBucket, "Yes"]

Resources:
    FirstS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !If [IsProduction, mytrainingproductionbucket, mytrainingdevbucket]

    SecondS3Bucket:
        Type: AWS::S3::Bucket
        Condition: IsMultiBucket
        Properties:
            BucketName: !If [IsMultiBucket, mysecondtrainingproductionbucket, mysecondtrainingdevbucket]
