AWSTemplateFormatVersion: "2010-09-09"
Description: Metadata example 4

Mappings: 
  RegionMap: 
    us-east-1: 
      AMI: "ami-0ff8a91507f77f867"
      TestAz: "us-east-1a"
    us-west-1: 
      AMI: "ami-0bdb828fd58c52235"
      TestAz: "us-west-1a"
    us-west-2: 
      AMI: "ami-a0cfeed8"
      TestAz: "us-west-2a"
    eu-west-1: 
      AMI: "ami-047bb4163c506cd98"
      TestAz: "eu-west-1a"
    sa-east-1: 
      AMI: "ami-07b14488da8ea02a0"
      TestAz: "sa-east-1a"
    ap-southeast-1: 
      AMI: "ami-08569b978cc4dfa10"
      TestAz: "ap-southeast-1a"
    ap-southeast-2: 
      AMI: "ami-09b42976632b27e9b"
      TestAz: "ap-southeast-2a"
    ap-northeast-1: 
      AMI: "ami-06cd52961ce9f0d85"
      TestAz: "ap-northeast-1a"

Parameters: 
  EnvType: 
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues: 
      - prod
      - test
    ConstraintDescription: must specify prod or test.

Conditions: 
  CreateProdResources: !Equals [ !Ref EnvType, prod ]

Resources: 
  EC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
  MountPoint: 
    Type: "AWS::EC2::VolumeAttachment"
    Condition: CreateProdResources
    Properties: 
      InstanceId: 
        !Ref EC2Instance
      VolumeId: 
        !Ref NewVolume
      Device: /dev/sdh
  NewVolume: 
    Type: "AWS::EC2::Volume"
    Condition: CreateProdResources
    Properties: 
      Size: 100
      AvailabilityZone: 
        !GetAtt EC2Instance.AvailabilityZone

Outputs: 
  VolumeId: 
    Condition: CreateProdResources
    Value: 
      !Ref NewVolume
    Export:
        Name: !Sub "${AWS::StackName}-VolumeId"
