AWSTemplateFormatVersion: 2010-09-09
Description: Metadata example 1

Metadata: 
    AWS::CloudFormation::Interface: 
      ParameterGroups: 
        - 
          Label: 
            default: "Network Configuration"
          Parameters: 
            - VPCID
            - SubnetId
            - SecurityGroupID
        - 
          Label: 
            default: "Amazon EC2 Configuration"
          Parameters: 
            - InstanceType
            - KeyName
      ParameterLabels: 
        VPCID: 
          default: "Which VPC should this be deployed to?"
  