AWSTemplateFormatVersion: 2010-09-09
Description: aws serverless example

Transform: AWS::Serverless-2016-10-31

Resources:
  Greetings:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: POST