AWSTemplateFormatVersion: 2010-09-09
Description: Prepare custom function

Resources:
  TrainingDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TrainingTable
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "Element"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "Element"
          KeyType: "HASH"
  
  MyCustomFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cloudformation-training-pawel
        S3Key: writetotable.zip
      Handler: writetotable.write2dynamo
      DeadLetterConfig: 
        TargetArn: !Ref MyCustomTopic
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Runtime: python3.6
      Timeout: 30

  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - sns:Subscribe
                  - sns:Publish
                Resource: !Ref MyCustomTopic

  MyCustomTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: MyCustomTopic
      TopicName: MyCustomTopic

Outputs:
  MyCustomFunctionArn:
    Description: ARN of the custom resource function.
    Value: !GetAtt 'MyCustomFunction.Arn'
    Export:
      Name: !Sub 'MyCustomFunctionArn'

  MyCustomTopicArn:
    Description: ARN of the SNS
    Value: !Ref MyCustomTopic
    Export:
      Name: MyCustomTopicArn